//------------------------------------------------------------------------------
// <auto-generated>
// Arohan.TollSphere - MIT Licensed.
// Author: Arohan-Infocare-TollSphere
// CreatedAt/Modified: 2025-07-18
// Handles ContactUpdatedEvent: triggered when a contact is updated.
// Extendable for additional actions (e.g., notifications, system updates).
// </auto-generated>
//------------------------------------------------------------------------------


namespace Arohan.TollSphere.Application.Features.Contacts.EventHandlers;

    public class ContactUpdatedEventHandler : INotificationHandler<ContactUpdatedEvent>
    {
        private readonly ILogger<ContactUpdatedEventHandler> _logger;

        public ContactUpdatedEventHandler(
            ILogger<ContactUpdatedEventHandler> logger
            )
        {
            _logger = logger;
        }
        public Task Handle(ContactUpdatedEvent notification, CancellationToken cancellationToken)
        {
            _logger.LogInformation("Handled domain event '{EventType}' for Contact ID: {ContactId}", 
                notification.GetType().Name, notification.Item?.Id);
            return Task.CompletedTask;
        }
    }
