//------------------------------------------------------------------------------
// <auto-generated>
// Arohan.TollSphere - MIT Licensed.
// Author: Arohan-Infocare-TollSphere
// CreatedAt/Modified: 2025-07-18
// Handles ContactCreatedEvent: triggered when a new contact is created.
// Extendable for additional actions (e.g., notifications, system updates).
// </auto-generated>
//------------------------------------------------------------------------------


namespace Arohan.TollSphere.Application.Features.Contacts.EventHandlers;

public class ContactCreatedEventHandler : INotificationHandler<ContactCreatedEvent>
{
        private readonly ILogger<ContactCreatedEventHandler> _logger;

        public ContactCreatedEventHandler(
            ILogger<ContactCreatedEventHandler> logger
            )
        {
            _logger = logger;
        }
        public Task Handle(ContactCreatedEvent notification, CancellationToken cancellationToken)
        {
            _logger.LogInformation("Handled domain event '{EventType}' for Contact ID: {ContactId}", 
                notification.GetType().Name, notification.Item?.Id);
            return Task.CompletedTask;
        }
}
