//------------------------------------------------------------------------------
// <auto-generated>
// Arohan.TollSphere - MIT Licensed.
// Author: Arohan-Infocare-TollSphere
// CreatedAt/Modified: 2025-07-18
// Validator for DeleteContactCommand: ensures the ID list for contact is not null and contains only positive IDs.
// Docs: https://docs.cleanarchitectureblazor.com/features/contact
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

namespace Arohan.TollSphere.Application.Features.Contacts.Commands.Delete;

public class DeleteContactCommandValidator : AbstractValidator<DeleteContactCommand>
{
        public DeleteContactCommandValidator()
        {
          
            RuleFor(v => v.Id).NotNull().ForEach(v=>v.GreaterThan(0));
          
        }
}
    

